services:
  mongodb:
    image: mongo:7
    container_name: roomdekho-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - roomdekho-mongo-data:/data/db

volumes:
  roomdekho-mongo-data:
